# Generated by Django 2.2.5 on 2020-02-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_pictures_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
